import { ConfigService } from '@nestjs/config';
import type { Repository } from 'typeorm';
import { Asset } from '../entities/asset.entity';
import { AssetPreviewService } from './asset-preview.service';
import { PreviewQueueService } from './preview-queue.service';

describe(AssetPreviewService.name, () => {
  const assetId = '11111111-1111-4111-8111-111111111111';
  const contentType =
    'application/vnd.openxmlformats-officedocument.presentationml.presentation';
  let asset: Asset;
  let assetsRepo: {
    findOne: jest.Mock;
    save: jest.Mock;
  };
  let queue: {
    enqueue: jest.Mock;
  };
  let service: AssetPreviewService;

  beforeEach(() => {
    asset = {
      id: assetId,
      type: 'file',
      filename: `${assetId}.pptx`,
      originalName: 'slides.pptx',
      contentType,
      size: 100,
      previewStatus: 'ready',
      previewSize: 80,
      previewErrorCode: null,
      previewGeneratorVersion: 'current-version',
      previewUpdatedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    assetsRepo = {
      findOne: jest.fn(async () => asset),
      save: jest.fn(async (value: Asset) => value),
    };
    queue = {
      enqueue: jest.fn(async () => undefined),
    };
    service = new AssetPreviewService(
      {
        get: jest.fn((key: string, fallback: unknown) =>
          key === 'app.previewGeneratorVersion' ? 'current-version' : fallback,
        ),
      } as unknown as ConfigService,
      assetsRepo as unknown as Repository<Asset>,
      queue as unknown as PreviewQueueService,
    );
  });

  it('keeps a preview generated by the current converter version', async () => {
    await expect(service.requestPreview(assetId)).resolves.toMatchObject({
      status: 'ready',
    });

    expect(assetsRepo.save).not.toHaveBeenCalled();
    expect(queue.enqueue).not.toHaveBeenCalled();
  });

  it('regenerates a preview produced by an outdated converter version', async () => {
    asset.previewGeneratorVersion = 'old-version';

    await expect(service.requestPreview(assetId)).resolves.toMatchObject({
      status: 'pending',
      url: null,
    });

    expect(asset).toMatchObject({
      previewStatus: 'pending',
      previewSize: null,
      previewErrorCode: null,
    });
    expect(assetsRepo.save).toHaveBeenCalledWith(asset);
    expect(queue.enqueue).toHaveBeenCalledWith(assetId);
  });
});
